version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-sha1-cache-
      - run:
          command: |
            readonly path="/home/circleci/.sha1_cache"
            readonly file="$path/$CIRCLE_BRANCH"
            sha1=""
            if [ -f $file ]; then
              sha1=$(head -n 1 $file)
            fi
            if [ ! -d $path ]; then
              mkdir $path
            fi
            if [ $sha1 = $CIRCLE_SHA1 ]; then
              echo "{\"runnable\": false}" > parameters.json
            else
              echo "{\"runnable\": true}" > parameters.json
            fi
            echo $CIRCLE_SHA1 > $file
      - save_cache:
          key: v1-sha1-cache-{{ epoch }}
          paths:
            - /home/circleci/.sha1_cache
      - continuation/continue:
          configuration_path: ./.circleci/configs/build.yml
          parameters: ./parameters.json

workflows:
  setup:
    jobs:
      - setup
